# Generated by Django 4.1.7 on 2023-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsersDataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=40)),
                ("file", models.FileField(upload_to="pdf")),
                ("json", models.FileField(upload_to="json")),
            ],
        ),
    ]
