# Generated by Django 4.1.7 on 2023-05-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dla", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersdataupload",
            name="json",
            field=models.CharField(max_length=200),
        ),
    ]
