# Generated by Django 4.1.7 on 2023-05-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dla", "0002_alter_usersdataupload_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersdataupload",
            name="html",
            field=models.CharField(default="default", max_length=200),
        ),
        migrations.AlterField(
            model_name="usersdataupload",
            name="json",
            field=models.CharField(default="default", max_length=200),
        ),
    ]
